from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    ListFlowable,
    ListItem
)
from reportlab.lib import colors
from app.pdf.styles import PAGE_SIZE, MARGIN, TITLE, H2, BODY, SMALL
from datetime import datetime


def build_pdf(buffer, analysis: dict):
    doc = SimpleDocTemplate(
        buffer,
        pagesize=PAGE_SIZE,
        rightMargin=MARGIN,
        leftMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
    )

    story = []

    master = analysis["master"]
    clinical = analysis["clinical"]
    patent = analysis["patent"]
    synthesis = analysis["synthesis"]

    # ================================
    # TITLE
    # ================================
    story.append(Paragraph("Drug Repurposing Assessment Report", TITLE))
    story.append(Paragraph(
        f"<b>Drug:</b> {master['drug']} &nbsp;&nbsp; "
        f"<b>Indication:</b> {master['indication']}<br/>"
        f"<b>Date:</b> {datetime.utcnow().strftime('%Y-%m-%d')}<br/>"
        f"<b>Generated by:</b> RepurposeAI",
        SMALL
    ))
    story.append(Spacer(1, 16))

    # ================================
    # HYPOTHESIS SCORE
    # ================================
    score = synthesis["hypothesis_strength_score"]["value"]
    story.append(Paragraph("Hypothesis Strength", H2))
    story.append(Paragraph(f"<b>{score} / 10</b>", BODY))

    story.append(ListFlowable(
        [
            ListItem(Paragraph(r, BODY))
            for r in synthesis["hypothesis_strength_score"]["rationale"]
        ],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 14))

    # ================================
    # OPPORTUNITY SUMMARY
    # ================================
    story.append(Paragraph("Opportunity Summary", H2))
    story.append(Paragraph(synthesis["opportunity_summary"], BODY))

    story.append(Spacer(1, 18))

    # ================================
    # CLINICAL EVIDENCE TABLE
    # ================================
    story.append(Paragraph("Clinical Evidence", H2))

    table_data = [
        ["Study", "Type", "Signal", "Outcome", "Limitations"]
    ]

    for e in clinical["evidence"]:
        table_data.append([
            e["source_id"],
            e["study_type"],
            e["statistical_signal"],
            e["outcome_summary"],
            "; ".join(e["limitations"])
        ])

    table = Table(table_data, repeatRows=1, colWidths=[70, 80, 60, 160, 120])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    story.append(table)
    story.append(Spacer(1, 12))

    story.append(ListFlowable(
        [
            ListItem(Paragraph(n, SMALL))
            for n in clinical["confidence_notes"]
        ],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 18))

    # ================================
    # PATENT ANALYSIS
    # ================================
    story.append(Paragraph("Patent Landscape", H2))
    story.append(Paragraph(
        f"<b>Freedom to Operate:</b> {patent['freedom_to_operate'].capitalize()}",
        BODY
    ))

    story.append(ListFlowable(
        [
            ListItem(Paragraph(p["patent_id"], BODY))
            for p in patent["key_patents"]
        ],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 8))
    story.append(ListFlowable(
        [ListItem(Paragraph(r, BODY)) for r in patent["risks"]],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 18))

    # ================================
    # DECISION GUIDANCE
    # ================================
    story.append(Paragraph("Decision Guidance", H2))

    story.append(Paragraph("Aligned Signals", BODY))
    story.append(ListFlowable(
        [ListItem(Paragraph(s, BODY)) for s in synthesis["aligned_signals"]],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Key Risks", BODY))
    story.append(ListFlowable(
        [ListItem(Paragraph(r, BODY)) for r in synthesis["key_risks"]],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Recommended Next Steps", BODY))
    story.append(ListFlowable(
        [ListItem(Paragraph(s, BODY)) for s in synthesis["recommended_next_steps"]],
        bulletType="bullet"
    ))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Explicit Limitations", BODY))
    story.append(ListFlowable(
        [ListItem(Paragraph(l, BODY)) for l in synthesis["explicit_limitations"]],
        bulletType="bullet"
    ))

    doc.build(story)
